name: All Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-20.04

    services:
      postgres:
        image: postgres:11-alpine
        env:
          POSTGRES_PASSWORD: ckan
          POSTGRES_USER: ckan
          POSTGRES_DB: ckan
        options: >-
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

      solr:
        image: ckan/solr
        env:
          CKAN_SOLR_PASSWORD: ckan
        ports:
          - 8983:8983

    strategy:
      matrix:
        python-version: [ 2.7, 3.6, 3.7 ]
        ckan-version: [ 2.8, 2.9, "dev-v2.10" ]
        exclude:
          - python-version: 3.6
            ckan-version: 2.8
          - python-version: 3.7
            ckan-version: 2.8
          - python-version: 2.7
            ckan-version: "dev-v2.10"
          - python-version: 3.6
            ckan-version: "dev-v2.10"
      fail-fast: false
    env:
      CKAN_PATH: ./ckan
      USE_GLOBAL_PYTHON_ENV: "1"  # we won't be using a virtual environment

    steps:
      - uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install CKAN
        run: make ckan-install CKAN_VERSION=${{ matrix.ckan-version }}
      - name: Set up the test environment
        run: make create-test-db dev-setup
      - name: Run tests
        run: make test WITH_COVERAGE=1
      - name: Report to Coveralls
        uses: AndreMiras/coveralls-python-action@v20201129
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: "CKAN ${{ matrix.ckan-version }} / Python ${{matrix.python-version}} (${{ matrix.test_number }})"
          parallel: true

  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: AndreMiras/coveralls-python-action@v20201129
      with:
        github-token: ${{ secrets.github_token }}
        parallel-finished: true

