name: All Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-20.04

    services:
      postgres:
        image: postgres:11-alpine
        env:
          POSTGRES_PASSWORD: ckan
          POSTGRES_USER: ckan
          POSTGRES_DB: ckan
        options: >-
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

      solr:
        image: ckan/solr
        env:
          CKAN_SOLR_PASSWORD: ckan
        ports:
          - 8983:8983

    strategy:
      matrix:
        python-version: [ 3.8, 3.9 ]
        ckan-version: [ 2.9, "2.10" ]
    env:
      CKAN_PATH: ./ckan
      USE_GLOBAL_PYTHON_ENV: "1"  # we won't be using a virtual environment

    steps:
      - uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install CKAN
        run: make ckan-install CKAN_VERSION=${{ matrix.ckan-version }}
      - name: Set up the test environment
        run: make create-test-db dev-setup
      - name: Run tests
        run: make test
